### ISSUE TITLE
multiple iterations

### ISSUE THREAD

**Issue by Patrik9** [MarcosEllys/awesome-newman-html-template#6]
Hello, the template is amazing, unfortunately not usable with multiple iterations of same test. Do you plan to add this functionality?

**Comment by MarcosEllys** [comment]
Hello, I also know this problem, but unfortunately I can't solve it, this problem happens when newman processes the collection.

The core team has a issue opened since 24 Nov 2017 (See here [Newman HTML report error with pm.sendRequest #1303](https://github.com/postmanlabs/newman/issues/1303)) :disappointed_relieved:.

For now, we can only wait.
